// Generated by Wrangler on Mon Sep 23 2024 18:14:53 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  NODE_VERSION: '20'
  DATABASE_URL: string
  AUTH0_CLIENT_SECRET: string
  GOOGLE_CLIENT_SECRET: string
  AUTH0_DOMAIN: string
  AUTH0_CLIENT_ID: string
  GOOGLE_CLIENT_ID: string
  APP_URL: string
}
