// Generated by Wrangler on Fri Sep 13 2024 10:00:04 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  DATABASE_URL: string
  AUTH0_DOMAIN: string
  AUTH0_CLIENT_ID: string
  AUTH0_CLIENT_SECRET: string
  GOOGLE_CLIENT_ID: string
  GOOGLE_CLIENT_SECRET: string
  CALLBACK_URL: string
}
