// Generated by Wrangler on Mon Sep 23 2024 17:45:03 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

interface Env {
  NODE_VERSION: '20'
  AUTH0_DOMAIN: 'dev-fqlx2duj4fgl8np2.us.auth0.com'
  AUTH0_CLIENT_ID: 'NmAJPXqBiYuiXmbtDUS1G3fW98GADhdl'
  GOOGLE_CLIENT_ID: ' '
  APP_URL: 'http://localhost:5173'
  DATABASE_URL: string
  AUTH0_CLIENT_SECRET: string
  GOOGLE_CLIENT_SECRET: string
}
