#:schema node_modules/wrangler/config-schema.json
name = "sscan-app"
send_metrics = false
compatibility_date = "2024-09-22"
compatibility_flags = ["nodejs_compat_v2"]
pages_build_output_dir = "./build/client"

[placement]
mode = "off"

[vars]
NODE_VERSION = "20"
AUTH0_DOMAIN="dev-fqlx2duj4fgl8np2.us.auth0.com"
AUTH0_CLIENT_ID="NmAJPXqBiYuiXmbtDUS1G3fW98GADhdl"
GOOGLE_CLIENT_ID=" "
APP_URL="http://localhost:5173"

[env.production.placement]
mode = "smart"

[env.production.vars]
NODE_VERSION = "20"
AUTH0_DOMAIN="dev-fqlx2duj4fgl8np2.us.auth0.com"
AUTH0_CLIENT_ID="NmAJPXqBiYuiXmbtDUS1G3fW98GADhdl"
GOOGLE_CLIENT_ID=""
APP_URL="https://sscan.nwlnexus.xyz"