DATABASE_URL="postgresql://{{op://Dev/j4l6atlxjujgovgeetxtxxoy64/username}}:{{op://Dev/j4l6atlxjujgovgeetxtxxoy64/password}}@{{op://Dev/j4l6atlxjujgovgeetxtxxoy64/server}}/{{op://Dev/j4l6atlxjujgovgeetxtxxoy64/database}}?schema=public&sslmode=require"
AUTH0_DOMAIN="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/AUTH0_DOMAIN}}"
AUTH0_CLIENT_ID="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/AUTH0_CLIENT_ID}}"
AUTH0_CLIENT_SECRET="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/AUTH0_CLIENT_SECRET}}"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""
CALLBACK_URL="http://localhost:5173/auth"