DATABASE_URL="{{op://Dev/j4l6atlxjujgovgeetxtxxoy64/DATABASE_URL}}"
AUTH0_DOMAIN="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/AUTH0_DOMAIN}}"
AUTH0_CLIENT_ID="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/AUTH0_CLIENT_ID}}"
AUTH0_CLIENT_SECRET="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/AUTH0_CLIENT_SECRET}}"
GOOGLE_CLIENT_ID="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/GOOGLE_CLIENT_ID}}"
GOOGLE_CLIENT_SECRET="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/GOOGLE_CLIENT_SECRET}}"
CALLBACK_URL="{{op://Dev/u2djddditxramzdmcemimb4lbq/${SECTION}/CALLBACK_URL}}/auth"