// Generated by Wrangler on Sun Sep 08 2024 12:56:02 GMT-0400 (Eastern Daylight Time)
// by running `wrangler types`

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
interface Env {}
