name: 'Deploy Pages applications'

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_org:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'nwlnexus'
    steps:
      - name: 🔍 Check organization
        run: echo "Running workflow for nwlnexus organization"

  determine_env:
    needs: check_org
    runs-on: ubuntu-latest
    outputs:
      determined_env: ${{ steps.set_env.outputs.env }}
    steps:
      - name: 🔍 Determine environment
        id: set_env
        run: |
          if [[ ${{ github.ref }} == "refs/heads/release" ]]; then
            echo "Environment: production"
            echo "env=PROD" >> $GITHUB_OUTPUT
          else
            echo "Environment: development"
            echo "env=DEV" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: determine_env
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Setup
        uses: ./tooling/github/setup
        with:
          op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

      - name: 🔐 Load secrets
        uses: 1password/load-secrets-action@v2
        id: load_secrets
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_API_TOKEN: op://Dev/jwis7zcfc2tcrvm4qxsw4mhknu/global_key
          CLOUDFLARE_ACCOUNT_ID: op://Dev/jwis7zcfc2tcrvm4qxsw4mhknu/account_id
          VITE_SESSION_SECRET: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/session_secret
          DATABASE_URL: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/DATABASE_URL
          AUTH0_DOMAIN: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/AUTH0_DOMAIN
          AUTH0_CLIENT_ID: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/AUTH0_CLIENT_ID
          AUTH0_CLIENT_SECRET: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/AUTH0_CLIENT_SECRET
          GOOGLE_CLIENT_ID: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/GOOGLE_CLIENT_ID
          GOOGLE_CLIENT_SECRET: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/GOOGLE_CLIENT_SECRET
          CALLBACK_URL: op://Dev/u2djddditxramzdmcemimb4lbq/${{ needs.determine_env.outputs.determined_env }}/CALLBACK_URL

      - name: 📝 Run migrations
        run: pnpm run db:migrate

      - name: 📦 Build
        working-directory: ./apps/web
        run: pnpm run build

      - name: 🚀 Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ steps.load_secrets.outputs.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ steps.load_secrets.outputs.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sscan
          directory: ./build/client
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          workingDirectory: ./apps/web
          wranglerVersion: '3'
